name: con_colegas
description: Another mobile application just like another

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  freezed_annotation: ^2.4.1
  slang: ^3.28.0
  slang_flutter: ^3.28.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/app_logo.png
